/** @deprecated Import from `@/lib/seo/lms` */
export {
  LMS_BASE_KEYWORDS,
  LMS_BERITA_KEGIATAN_PATH,
  LMS_BERITA_KEGIATAN_SLUG,
  LMS_PAGE_SEO,
  LMS_PUBLIC_PATHS,
  LMS_SITEMAP_ENTRIES,
  PPDB_SCHOOL_LOCALITY,
  PPDB_SCHOOL_LOCATION,
  PPDB_SCHOOL_NPSN,
  PPDB_SCHOOL_REGION,
  buildConsoleAbsoluteUrl,
  buildLmsBreadcrumbJsonLd,
  buildLmsDashboardMetadata,
  buildLmsEducationalOrganizationJsonLd,
  buildLmsLandingMetadata,
  buildLmsPageMetadata,
  buildLmsSoftwareApplicationJsonLd,
  buildLmsWebApplicationJsonLd,
  buildLmsWebPageJsonLd,
  resolveLmsOgImageUrl,
  type LmsBreadcrumbItem,
  type LmsPageId,
  type LmsPageSeoInput,
} from "@/lib/seo/lms";
