/** @deprecated Import from `@/lib/seo/ppdb` */
export {
  PPDB_BASE_KEYWORDS,
  PPDB_JURUSAN_PROGRAMS,
  PPDB_PAGE_SEO,
  PPDB_PUBLIC_PATHS,
  PPDB_SCHOOL_ACCREDITATION,
  PPDB_SCHOOL_LOCALITY,
  PPDB_SCHOOL_LOCATION,
  PPDB_SCHOOL_NPSN,
  PPDB_SCHOOL_REGION,
  PPDB_SITEMAP_ENTRIES,
  buildPpdbAbsoluteUrl,
  buildPpdbBreadcrumbJsonLd,
  buildPpdbCourseJsonLd,
  buildPpdbDaftarMetadata,
  buildPpdbDaftarSuksesMetadata,
  buildPpdbEducationalOrganizationJsonLd,
  buildPpdbFaqPageJsonLd,
  buildPpdbHubMetadata,
  buildPpdbPageMetadata,
  buildPpdbWebPageJsonLd,
  resolvePpdbOgImageUrl,
  type PpdbBreadcrumbItem,
  type PpdbPageId,
  type PpdbPageSeoInput,
} from "@/lib/seo/ppdb";
